version: '3.1'
services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    environment: 
      RABBITMQ_DEFAULT_USER: my-rabbit
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 15672:15672
      - 5672:5672
      - 25676:25676