# Use the official image as a parent image.
# Change the "yourPasswordHere" field and ports if necessary 
version: "3"
services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass yourPasswordHere
    ports:
      - "6379:6379"
